#! /bin/bash

#
# web用に動画をエンコードする
# ./encode-video-web in1 in2 ... out
#

source $(dirname $0)/_util.sh

LANG=ja_JP.UTF-8
args=("$@")

dst=${args[${#args[@]}-1]}
unset 'args[${#args[@]}-1]'

inputs=$(join_by '|' ${args[@]})

bash -ex <<END
ffmpeg -hide_banner -y -i "concat:${inputs}" \
  -vf 'bwdif=0:-1:0' -f webm -c:v libvpx -threads 0 \
  -c:a libvorbis -b:a 128k \
  -strict -2 \
  -pass 1 \
  ${dst}
ffmpeg -hide_banner -y -i "concat:${inputs}" \
-vf 'bwdif=0:-1:0' -f webm -c:v libvpx -threads 0 \
-c:a libvorbis -b:a 128k \
  -strict -2 \
  -pass 2 \
  ${dst}
END
rm -f ffmpeg2pass-0.log ffmpeg2pass-0.log.mbtree
echo 'All done, have fun!'
