#! /bin/bash

#
# フォルダ中の画像に適切なハッシュ値をつける
# ./hash-images <dir>
#

for fname in *.jpg *.JPG *.jpeg *.tiff *.png *.gif; do
  [ -e "${fname}" ] || continue;
  hash=$(md5sum ${fname} | awk '{ print $1 }')
  mv "${fname}" "${hash}.${fname##*.}"
done
