#! /bin/bash

#
# フォルダ中の画像に適切なハッシュ値をつける
# ./img-hash <dir>
#

set -eu

dir="."
if [[ $# > 0 ]]; then
  dir="$1"
  shift
fi
cd $dir

for fname in *.jpg *.JPG *.jpeg *.tiff *.tif *.png *.gif; do
  [ -e "${fname}" ] || continue;
  hash=$(md5sum "${fname}" | awk '{ print $1 }')
  [ -e "${hash}.${fname##*.}" ] && continue;
  mv "${fname}" "${hash}.${fname##*.}"
done
