#! /bin/bash

#
# フォルダ中のスキャンした画像に適切なハッシュ値をつける
# ./img-rename-scan <dir>
#

set -eu

dir="."
if [[ $# > 0 ]]; then
  dir="$1"
  shift
fi
cd $dir

for fname in *.tiff; do
  [ -e "${fname}" ] || continue;
  hash=$(md5sum ${fname} | awk '{ print $1 }')
  mv "${fname}" "${hash}.tiff"
  # jpegに現像したら、セットでそれらも（tiffのハッシュ値にあわせて）変更する
  if [ -e "${fname//.tiff}".jpeg ]; then
    mv "${fname//.tiff}".jpeg ${hash}.jpeg
  fi
  if [ -e "${fname//.tiff}".jpg ]; then
    mv "${fname//.tiff}".jpg ${hash}.jpg
  fi
done
