#! /bin/bash

#
# フォルダ中のスキャンした画像に適切なハッシュ値をつける
# ./img-rename-scan <dir>
#

set -eu

dir="."
if [[ $# > 0 ]]; then
  dir="$1"
  shift
fi
cd $dir

for fname in *.tiff; do
  [ -e "${fname}" ] || continue;
  if [[ -e "${hash}.tiff" ]]; then
    base="${fname//.tiff}"
    ext="tiff"
  elif [[ -e "${hash}.tif" ]]; then
    base="${fname//.tif}"
    ext="tif"
  else
    continue
  fi
  hash=$(md5sum "${fname}" | awk '{ print $1 }')
  mv "${fname}" "${hash}.${ext}"
  # 現像したら、セットでそれらも（tiffのハッシュ値にあわせて）変更する
  if [ -e "${base}.jpeg" ]; then
    mv "${base}.jpeg" "${hash}.jpeg"
  fi
  if [ -e "${base}.jpg" ]; then
    mv "${base}.jpeg" "${hash}.jpg"
  fi
  if [ -e "${base}.png" ]; then
    mv "${base}.png" "${hash}.png"
  fi
  if [ -e "${base}.xcf" ]; then
    mv "${base}.xcf" "${hash}.xcf"
  fi
done
