#! /bin/bash

#
# タイムラプスビデオを作成
# ./make-timelapse-video in out
#
source $(dirname $0)/_util.sh

LANG=ja_JP.UTF-8
echo -n "speed factor: "
read speed

echo -n "fps: "
read fps

args=("$@")
dst=${args[${#args[@]}]}
unset 'args[${#args[@]}]'
inputs=$(join_by '|' ${args[@]})
out="${dst%.*}-out${speed}x${fps}fps.mp4"

  bash -ex <<END
  ffmpeg -hide_banner -y -i "concat:${inputs}" \
  -filter "bwdif=0:-1:0,setpts=PTS/${speed},minterpolate='mi_mode=mci:mc_mode=aobmc:vsbmc=1:fps=${fps}'" \
  -c:v libx264 -profile:v high -preset veryslow -crf 20 -threads 0 \
  -strict -2 \
  -pass 1 \
  -an \
  "${out}" 2> /dev/null

  ffmpeg -hide_banner -y -i "concat:${inputs}" \
  -filter "bwdif=0:-1:0,setpts=PTS/${speed},minterpolate='mi_mode=mci:mc_mode=aobmc:vsbmc=1:fps=${fps}'" \
  -c:v libx264 -profile:v high -preset veryslow -crf 20 -threads 0 \
  -strict -2 \
  -pass 2 \
  -an \
  "${out}" 2> /dev/null
END

rm -f ffmpeg2pass-0.log ffmpeg2pass-0.log.mbtree
echo "All done, have fun!"
