#! /bin/bash

#
# 連番画像からPDFを作成
# ./pdf-from-images in-dir out.pdf
#

set -eu

if (( $# < 1 )); then
  echo "usage pdf from-images <dirname> <out.pdf>"
  exit -1
fi

dir="."
if [[ $# > 0 ]]; then
  dir="$1"
  shift
fi

fname="$(basename "${dir}").pdf"
if [[ $# > 0 ]]; then
  fname="$1"
  shift
fi

inputs=$(find "$(cd "$(readlink -f "$dir")" && pwd)" -mindepth 1 -maxdepth 1 -type f -regex ".*\.\(jpg\|gif\|png\|jpeg\)" | sort --numeric-sort | tr "\n" "\0" | xargs -0 --max-lines=1 printf "'%s' ")
eval "magick convert -verbose ${inputs} '${fname}'"
