#! /bin/bash

#
# フォルダ中の画像をすべてリサイズする
# ./resize-images <dir>
#

DIR=$1
if [ -z "${DIR}" ]; then
  DIR="."
fi
QUALITY=85%
SIZE=1600x1600

for file in ${DIR}/*; do
  if echo ${file} | grep '.resized.jpg$'; then
    continue
  fi
  if (file -b "${file}" | grep 'image data' > /dev/null 2>&1); then
    echo "[Processing] ${file} -> ${file%.*}.resized.jpg"
    convert "${file}" -quality ${QUALITY} -resize ${SIZE} "${file%.*}.resized.jpg"
  fi
done
