#! /bin/bash

#
# 複数のビデオを連結
# ./video-cat in1 in2 ... out
#

set -eu

if (( $# < 2 )); then
  echo "usage video cat <in1> <in2> ... <out>"
  exit -1
fi

source $(dirname $0)/_util.sh

LANG=ja_JP.UTF-8
args=("$@")

dst=${args[${#args[@]}-1]}
unset 'args[${#args[@]}-1]'

inputs=$(join_by '|' ${args[@]})
bash -ex <<EOF
ffmpeg -i "concat:${inputs}" -c copy ${dst}
EOF
echo 'All done, have fun!'
